(()=>{
 const baseNorm=normalizeState; normalizeState=function(input){const tasks=input&&Array.isArray(input.tasks)?input.tasks:[];const o=baseNorm(input);o.tasks=tasks.map(t=>({id:t.id||uid(),title:t.title||'Aufgabe',due:t.due||'',priority:['high','normal','low'].includes(t.priority)?t.priority:'normal',category:t.category||'',duration:Number(t.duration||0),note:t.note||'',done:!!t.done,doneAt:t.doneAt||null,eventId:t.eventId||null,createdAt:t.createdAt||new Date().toISOString()}));return o};state=normalizeState(state);
 const st=document.createElement('style');st.textContent='.task-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.task-stat{background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:9px}.task-stat b{display:block;font-size:18px}.task-item{padding:12px 0;border-bottom:1px solid var(--line)}.task-item:last-child{border-bottom:0}.task-head{display:flex;justify-content:space-between;gap:8px}.task-title{font-weight:800}.task-title.done{text-decoration:line-through;opacity:.55}.task-meta{font-size:11px;color:var(--muted);margin-top:4px}.task-category{font-weight:700}.task-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.task-actions button{padding:7px 9px;font-size:11px}.task-prio{font-size:10px;font-weight:800;background:#f1f5f9;border-radius:999px;padding:3px 7px;height:max-content}.task-prio.high{background:#fee2e2;color:#991b1b}.task-prio.low{background:#e0f2fe;color:#075985}';document.head.appendChild(st);
 const $=id=>document.getElementById(id),esc=v=>String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
 function ev(t){return t.eventId?state.events.find(e=>e.id===t.eventId):null} function pl(p){return p==='high'?'Hoch':p==='low'?'Niedrig':'Normal'}
 function categoryColor(name){
   const key=String(name||'').trim().toLocaleLowerCase('de-DE');
   let hash=0;
   for(let i=0;i<key.length;i++) hash=((hash<<5)-hash+key.charCodeAt(i))|0;
   const hue=((Math.abs(hash)*137.508)%360+360)%360;
   return `hsl(${hue.toFixed(0)} 68% 38%)`;
 }
 function item(t){const e=ev(t),rest=[t.due?'Fällig '+t.due:'',t.duration?t.duration+' Min.':'',e?'Geplant '+e.date+(e.start?' · '+e.start+'–'+e.end:''):'Nicht geplant'].filter(Boolean).join(' · '),meta=(t.category?`<span class="task-category" style="color:${categoryColor(t.category)}">${esc(t.category)}</span>${rest?' · ':''}`:'')+esc(rest);return `<div class="task-item"><div class="task-head"><div><div class="task-title ${t.done?'done':''}">${esc(t.title)}</div><div class="task-meta">${meta}</div></div><span class="task-prio ${t.priority}">${pl(t.priority)}</span></div><div class="task-actions"><button class="task-toggle ${t.done?'':'primary'}" data-id="${t.id}">${t.done?'↩ Offen':'✓ Erledigt'}</button><button class="task-plan" data-id="${t.id}">${e?'Termin ändern':'🗓 Planen'}</button><button class="task-edit" data-id="${t.id}">✎ Bearbeiten</button></div></div>`}
 function taskDate(t){return ev(t)?.date||t.due||'9999-12-31'}function sortTasks(a){return [...a].sort((x,y)=>{const dx=taskDate(x),dy=taskDate(y);if(dx!==dy)return dx.localeCompare(dy);const tx=ev(x)?.start||'23:59',ty=ev(y)?.start||'23:59';if(tx!==ty)return tx.localeCompare(ty);return String(x.title||'').localeCompare(String(y.title||''),'de')})}function render(){const today=iso(new Date()),all=state.tasks||[],open=sortTasks(all.filter(t=>!t.done)),done=sortTasks(all.filter(t=>t.done)),planned=sortTasks(open.filter(t=>ev(t))),unplanned=sortTasks(open.filter(t=>!ev(t))),tod=sortTasks(open.filter(t=>t.due===today||ev(t)?.date===today));$('taskSummary').innerHTML=`<div class="task-summary"><div class="task-stat"><span class="tiny">Offen</span><b>${open.length}</b></div><div class="task-stat"><span class="tiny">Nicht geplant</span><b>${unplanned.length}</b></div><div class="task-stat"><span class="tiny">Erledigt</span><b>${done.length}</b></div></div>`;$('tasksToday').innerHTML=tod.map(item).join('')||'<div class="tiny">Heute keine Aufgaben.</div>';$('tasksUnplanned').innerHTML=unplanned.map(item).join('')||'<div class="tiny">Alle offenen Aufgaben sind geplant.</div>';$('tasksPlanned').innerHTML=planned.map(item).join('')||'<div class="tiny">Noch keine geplanten Aufgaben.</div>';$('tasksDone').innerHTML=done.map(item).join('')||'<div class="tiny">Noch keine erledigten Aufgaben.</div>';document.querySelectorAll('.task-toggle').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.id);t.done=!t.done;t.doneAt=t.done?new Date().toISOString():null;save();render()});document.querySelectorAll('.task-edit').forEach(b=>b.onclick=()=>openTask(b.dataset.id));document.querySelectorAll('.task-plan').forEach(b=>b.onclick=()=>openPlan(b.dataset.id))}
 const modal=$('taskModal'),pm=$('taskPlanModal');function openTask(id){const t=id?state.tasks.find(x=>x.id===id):null;$('taskId').value=t?.id||'';$('taskTitle').value=t?.title||'';$('taskDue').value=t?.due||'';$('taskPriority').value=t?.priority||'normal';$('taskCategory').value=t?.category||'';$('taskDuration').value=t?.duration||'';$('taskNote').value=t?.note||'';$('deleteTaskBtn').style.display=t?'inline-block':'none';modal.classList.add('show')}
 $('addTaskBtn').onclick=()=>openTask();$('closeTaskModal').onclick=()=>modal.classList.remove('show');$('closeTaskPlanModal').onclick=()=>pm.classList.remove('show');$('taskForm').onsubmit=e=>{e.preventDefault();const id=$('taskId').value,t=id?state.tasks.find(x=>x.id===id):null,d={title:$('taskTitle').value.trim(),due:$('taskDue').value,priority:$('taskPriority').value,category:$('taskCategory').value.trim(),duration:Number($('taskDuration').value||0),note:$('taskNote').value.trim()};if(t)Object.assign(t,d);else state.tasks.push({id:uid(),...d,done:false,doneAt:null,eventId:null,createdAt:new Date().toISOString()});save();modal.classList.remove('show');render()};$('deleteTaskBtn').onclick=()=>{if(confirm('Aufgabe wirklich löschen?')){state.tasks=state.tasks.filter(x=>x.id!==$('taskId').value);save();modal.classList.remove('show');render()}};
 function openPlan(id){const t=state.tasks.find(x=>x.id===id),e=ev(t);$('taskPlanId').value=id;$('taskPlanName').textContent=t.title;$('taskPlanDate').value=e?.date||t.due||iso(new Date());$('taskPlanStart').value=e?.start||'18:00';$('taskPlanEnd').value=e?.end||'19:00';pm.classList.add('show')}$('taskPlanForm').onsubmit=e=>{e.preventDefault();const t=state.tasks.find(x=>x.id===$('taskPlanId').value);let e0=ev(t);if(e0)Object.assign(e0,{date:$('taskPlanDate').value,start:$('taskPlanStart').value,end:$('taskPlanEnd').value,note:'Aufgabe: '+t.title});else{e0={id:uid(),date:$('taskPlanDate').value,type:'Sonstiges',start:$('taskPlanStart').value,end:$('taskPlanEnd').value,paidHours:0,nightHours:0,sundayHours:0,holidayHours:0,note:'Aufgabe: '+t.title,bibMiniHours:0,workConfirmedAt:null};state.events.push(e0);t.eventId=e0.id}save();pm.classList.remove('show');renderAll();render()};document.querySelectorAll('[data-screen="tasks"]').forEach(b=>b.addEventListener('click',render));render();
})();
